openapi: 3.2.0
info:
  description: The future of fintech.
  title: Polygon Crypto:snapshot API
  version: 1.0.0
servers:
- description: Polygon Platform API
  url: https://api.polygon.io
- description: Polygon Platform API (Staging)
  url: https://api.staging.polygon.io
security:
- apiKey: []
tags:
- name: crypto:snapshot
paths:
  /v2/snapshot/locale/global/markets/crypto/tickers:
    get:
      description: 'Get the current minute, day, and previous day’s aggregate, as well as the last trade and quote for all traded cryptocurrency symbols.

        <br />

        <br />

        Note: Snapshot data is cleared at 12am EST and gets populated as data is received from the exchanges. This can happen as early as 4am EST.

        '
      operationId: GetCryptoSnapshotTickers
      parameters:
      - description: A case-sensitive comma separated list of tickers to get snapshots for. For example, X:BTCUSD, X:ETHBTC, and X:BOBAUSD. Empty string defaults to querying all tickers.
        in: query
        name: tickers
        schema:
          items:
            type: string
          type: array
      responses:
        '200':
          content:
            application/json:
              example:
                status: OK
                tickers:
                - day:
                    c: 0.296
                    h: 0.59714
                    l: 0.23706
                    o: 0.28
                    v: 4097699.5691991993
                    vw: 0
                  lastTrade:
                    c:
                    - 1
                    i: 413131
                    p: 0.293
                    s: 13.6191
                    t: 1605292686010
                    x: 17
                  min:
                    c: 0.296
                    h: 0.296
                    l: 0.294
                    n: 2
                    o: 0.296
                    t: 1684427880000
                    v: 123.4866
                    vw: 0
                  prevDay:
                    c: 0.281
                    h: 0.59714
                    l: 0.23706
                    o: 0.27
                    v: 6070178.786154971
                    vw: 0.4076
                  ticker: X:FSNUSD
                  todaysChange: 0.012
                  todaysChangePerc: 4.270463
                  updated: 1605330008999
              schema:
                allOf:
                - properties:
                    status:
                      description: The status of this request's response.
                      type: string
                  required:
                  - status
                  type: object
                - properties:
                    tickers:
                      description: An array of snapshot data for the specified tickers.
                      items:
                        properties:
                          day:
                            description: The most recent daily bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            type: object
                          fmv:
                            description: Fair market value is only available on Business plans. It is our proprietary algorithm to generate a real-time, accurate, fair market value of a tradable security. For more information, <a rel="nofollow" target="_blank" href="https://massive.com/contact">contact us</a>.
                            format: double
                            type: number
                          lastTrade:
                            description: The most recent trade for this ticker.
                            properties:
                              c:
                                description: The trade conditions.
                                items:
                                  type: integer
                                type: array
                              i:
                                description: 'The Trade ID which uniquely identifies a trade. These are unique per

                                  combination of ticker, exchange, and TRF. For example: A trade for AAPL

                                  executed on NYSE and a trade for AAPL executed on NASDAQ could potentially

                                  have the same Trade ID.

                                  '
                                type: string
                              p:
                                description: 'The price of the trade. This is the actual dollar value per whole share of

                                  this trade. A trade of 100 shares with a price of $2.00 would be worth a

                                  total dollar value of $200.00.

                                  '
                                format: double
                                type: number
                              s:
                                description: The size (volume) of the trade.
                                type: number
                              t:
                                description: The millisecond accuracy timestamp. This is the timestamp of when the trade was generated at the exchange.
                                type: integer
                              x:
                                description: "The exchange that this crypto trade happened on.  \nSee <a href=\"https://massive.com/docs/rest/crypto/market-operations/exchanges\">Exchanges</a> for a mapping of exchanges to IDs.\n"
                                type: integer
                            required:
                            - c
                            - i
                            - p
                            - s
                            - t
                            - x
                            type: object
                          min:
                            description: The most recent minute bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              n:
                                description: The number of transactions in the aggregate window.
                                type: integer
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              t:
                                description: The Unix millisecond timestamp for the start of the aggregate window.
                                type: integer
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            - t
                            - n
                            type: object
                          prevDay:
                            description: The previous day's bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            type: object
                          ticker:
                            description: The exchange symbol that this item is traded under.
                            type: string
                          todaysChange:
                            description: The value of the change from the previous day.
                            format: double
                            type: number
                          todaysChangePerc:
                            description: The percentage change since the previous day.
                            format: double
                            type: number
                          updated:
                            description: The last updated timestamp.
                            type: integer
                        required:
                        - day
                        - lastTrade
                        - min
                        - prevDay
                        - ticker
                        - todaysChange
                        - todaysChangePerc
                        - updated
                        type: object
                      type: array
                  type: object
            text/csv:
              example: 'day_c,day_h,day_l,day_o,day_v,lastTrade_c,lastTrade_i,lastTrade_p,lastTrade_s,lastTrade_t,lastTrade_x,min_c,min_h,min_l,min_o,min_v,prevDay_c,prevDay_h,prevDay_l,prevDay_o,prevDay_v,prevDay_vw

                16260.85,16428.4,15830.4,16418.07,105008.84231068,0,"[2]",464569520,16242.31,0.001933,1605294230780,4,16235.1,16264.29,16129.3,16257.51,19.30791925,0,16399.24,16418.07,16399.24,16418.07,0.99167108,16402.6893

                '
              schema:
                type: string
          description: Get current state for all tickers
        default:
          description: Unexpected error
      summary: All Tickers
      tags:
      - crypto:snapshot
      x-polygon-entitlement-allowed-timeframes:
      - description: Real Time Data
        name: realtime
      - description: 15 minute delayed data
        name: delayed
      x-polygon-entitlement-data-type:
        description: Aggregate data
        name: aggregates
      x-polygon-entitlement-market-type:
        description: Crypto data
        name: crypto
  /v2/snapshot/locale/global/markets/crypto/tickers/{ticker}:
    get:
      description: 'Get the current minute, day, and previous day’s aggregate, as well as the last trade and quote for a single traded cryptocurrency symbol.

        <br />

        <br />

        Note: Snapshot data is cleared at 12am EST and gets populated as data is received from the exchanges.

        '
      operationId: GetCryptoSnapshotTicker
      parameters:
      - description: Ticker of the snapshot
        example: X:BTCUSD
        in: path
        name: ticker
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                request_id: ad92e92ce183112c593717f00dfebd2c
                status: OK
                ticker:
                  day:
                    c: 16260.85
                    h: 16428.4
                    l: 15830.4
                    o: 16418.07
                    v: 105008.84231068
                    vw: 0
                  lastTrade:
                    c:
                    - 2
                    i: '464569520'
                    p: 16242.31
                    s: 0.001933
                    t: 1605294230780
                    x: 4
                  min:
                    c: 16235.1
                    h: 16264.29
                    l: 16129.3
                    n: 558
                    o: 16257.51
                    t: 1684428960000
                    v: 19.30791925
                    vw: 0
                  prevDay:
                    c: 16399.24
                    h: 16418.07
                    l: 16399.24
                    o: 16418.07
                    v: 0.99167108
                    vw: 16402.6893
                  ticker: X:BTCUSD
                  todaysChange: -156.93
                  todaysChangePerc: -0.956935
                  updated: 1605330008999
              schema:
                allOf:
                - properties:
                    status:
                      description: The status of this request's response.
                      type: string
                  required:
                  - status
                  type: object
                - properties:
                    request_id:
                      description: A request id assigned by the server.
                      type: string
                  required:
                  - request_id
                  type: object
                - properties:
                    ticker:
                      description: Contains the requested snapshot data for the specified ticker.
                      properties:
                        day:
                          description: The most recent daily bar for this ticker.
                          properties:
                            c:
                              description: The close price for the symbol in the given time period.
                              format: double
                              type: number
                            h:
                              description: The highest price for the symbol in the given time period.
                              format: double
                              type: number
                            l:
                              description: The lowest price for the symbol in the given time period.
                              format: double
                              type: number
                            o:
                              description: The open price for the symbol in the given time period.
                              format: double
                              type: number
                            v:
                              description: The trading volume of the symbol in the given time period.
                              format: double
                              type: number
                            vw:
                              description: The volume weighted average price.
                              format: double
                              type: number
                          required:
                          - o
                          - h
                          - l
                          - c
                          - v
                          - vw
                          type: object
                        fmv:
                          description: Fair market value is only available on Business plans. It is our proprietary algorithm to generate a real-time, accurate, fair market value of a tradable security. For more information, <a rel="nofollow" target="_blank" href="https://massive.com/contact">contact us</a>.
                          format: double
                          type: number
                        lastTrade:
                          description: The most recent trade for this ticker.
                          properties:
                            c:
                              description: The trade conditions.
                              items:
                                type: integer
                              type: array
                            i:
                              description: 'The Trade ID which uniquely identifies a trade. These are unique per

                                combination of ticker, exchange, and TRF. For example: A trade for AAPL

                                executed on NYSE and a trade for AAPL executed on NASDAQ could potentially

                                have the same Trade ID.

                                '
                              type: string
                            p:
                              description: 'The price of the trade. This is the actual dollar value per whole share of

                                this trade. A trade of 100 shares with a price of $2.00 would be worth a

                                total dollar value of $200.00.

                                '
                              format: double
                              type: number
                            s:
                              description: The size (volume) of the trade.
                              type: number
                            t:
                              description: The millisecond accuracy timestamp. This is the timestamp of when the trade was generated at the exchange.
                              type: integer
                            x:
                              description: "The exchange that this crypto trade happened on.  \nSee <a href=\"https://massive.com/docs/rest/crypto/market-operations/exchanges\">Exchanges</a> for a mapping of exchanges to IDs.\n"
                              type: integer
                          required:
                          - c
                          - i
                          - p
                          - s
                          - t
                          - x
                          type: object
                        min:
                          description: The most recent minute bar for this ticker.
                          properties:
                            c:
                              description: The close price for the symbol in the given time period.
                              format: double
                              type: number
                            h:
                              description: The highest price for the symbol in the given time period.
                              format: double
                              type: number
                            l:
                              description: The lowest price for the symbol in the given time period.
                              format: double
                              type: number
                            n:
                              description: The number of transactions in the aggregate window.
                              type: integer
                            o:
                              description: The open price for the symbol in the given time period.
                              format: double
                              type: number
                            t:
                              description: The Unix millisecond timestamp for the start of the aggregate window.
                              type: integer
                            v:
                              description: The trading volume of the symbol in the given time period.
                              format: double
                              type: number
                            vw:
                              description: The volume weighted average price.
                              format: double
                              type: number
                          required:
                          - o
                          - h
                          - l
                          - c
                          - v
                          - vw
                          - t
                          - n
                          type: object
                        prevDay:
                          description: The previous day's bar for this ticker.
                          properties:
                            c:
                              description: The close price for the symbol in the given time period.
                              format: double
                              type: number
                            h:
                              description: The highest price for the symbol in the given time period.
                              format: double
                              type: number
                            l:
                              description: The lowest price for the symbol in the given time period.
                              format: double
                              type: number
                            o:
                              description: The open price for the symbol in the given time period.
                              format: double
                              type: number
                            v:
                              description: The trading volume of the symbol in the given time period.
                              format: double
                              type: number
                            vw:
                              description: The volume weighted average price.
                              format: double
                              type: number
                          required:
                          - o
                          - h
                          - l
                          - c
                          - v
                          - vw
                          type: object
                        ticker:
                          description: The exchange symbol that this item is traded under.
                          type: string
                        todaysChange:
                          description: The value of the change from the previous day.
                          format: double
                          type: number
                        todaysChangePerc:
                          description: The percentage change since the previous day.
                          format: double
                          type: number
                        updated:
                          description: The last updated timestamp.
                          type: integer
                      required:
                      - day
                      - lastTrade
                      - min
                      - prevDay
                      - ticker
                      - todaysChange
                      - todaysChangePerc
                      - updated
                      type: object
                  type: object
            text/csv:
              example: 'day_c,day_h,day_l,day_o,day_v,lastTrade_c,lastTrade_i,lastTrade_p,lastTrade_s,lastTrade_t,lastTrade_x,min_c,min_h,min_l,min_o,min_v,prevDay_c,prevDay_h,prevDay_l,prevDay_o,prevDay_v,prevDay_vw

                16260.85,16428.4,15830.4,16418.07,105008.84231068,0,"[2]",464569520,16242.31,0.001933,1605294230780,4,16235.1,16264.29,16129.3,16257.51,19.30791925,0,16399.24,16418.07,16399.24,16418.07,0.99167108,16402.6893

                '
              schema:
                type: string
          description: Get current state for a ticker
        default:
          description: Unexpected error
      summary: Ticker
      tags:
      - crypto:snapshot
      x-polygon-entitlement-allowed-timeframes:
      - description: Real Time Data
        name: realtime
      - description: 15 minute delayed data
        name: delayed
      x-polygon-entitlement-data-type:
        description: Aggregate data
        name: aggregates
      x-polygon-entitlement-market-type:
        description: Crypto data
        name: crypto
  /v2/snapshot/locale/global/markets/crypto/tickers/{ticker}/book:
    get:
      description: 'Get the current level 2 book of a single ticker. This is the combined book from all of the exchanges.

        <br />

        <br />

        Note: Snapshot data is cleared at 12am EST and gets populated as data is received from the exchanges.

        '
      operationId: DeprecatedGetCryptoSnapshotTickerBook
      parameters:
      - description: The cryptocurrency ticker.
        example: X:BTCUSD
        in: path
        name: ticker
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                  askCount: 593.1412981600005
                  asks:
                  - p: 11454
                    x:
                      '2': 1
                  - p: 11455
                    x:
                      '2': 1
                  bidCount: 694.951789670001
                  bids:
                  - p: 16303.17
                    x:
                      '1': 2
                  - p: 16302.94
                    x:
                      '1': 0.02859424
                      '6': 0.023455
                  spread: -4849.17
                  ticker: X:BTCUSD
                  updated: 1605295074162
                status: OK
              schema:
                allOf:
                - description: The status of this request's response.
                  type: string
                - properties:
                    data:
                      properties:
                        askCount:
                          description: The combined total number of asks in the book.
                          format: double
                          type: number
                        asks:
                          items:
                            properties:
                              p:
                                description: The price of this book level.
                                format: double
                                type: number
                              x:
                                description: "A map of the exchange ID to number of shares at this price level.\n<br />\n<br />\n**Example:**\n<br />\n`{\n  \"p\": 16302.94,\n  \"x\": {\n    \"1\": 0.02859424,\n    \"6\": 0.023455\n  }\n}`\n<br />\n<br />\nIn this example, exchange ID 1 has 0.02859424 shares available at $16,302.94,\nand exchange ID 6 has 0.023455 shares at the same price level.\n"
                                type: object
                            required:
                            - p
                            - x
                            type: object
                          type: array
                        bidCount:
                          description: The combined total number of bids in the book.
                          format: double
                          type: number
                        bids:
                          items:
                            properties:
                              p:
                                description: The price of this book level.
                                format: double
                                type: number
                              x:
                                description: "A map of the exchange ID to number of shares at this price level.\n<br />\n<br />\n**Example:**\n<br />\n`{\n  \"p\": 16302.94,\n  \"x\": {\n    \"1\": 0.02859424,\n    \"6\": 0.023455\n  }\n}`\n<br />\n<br />\nIn this example, exchange ID 1 has 0.02859424 shares available at $16,302.94,\nand exchange ID 6 has 0.023455 shares at the same price level.\n"
                                type: object
                            required:
                            - p
                            - x
                            type: object
                          type: array
                        spread:
                          description: The difference between the best bid and the best ask price across exchanges.
                          format: double
                          type: number
                        ticker:
                          description: The exchange symbol that this item is traded under.
                          type: string
                        updated:
                          description: The last updated timestamp.
                          type: integer
                      required:
                      - ticker
                      - bids
                      - asks
                      - bidCount
                      - askCount
                      - spread
                      - updated
                      type: object
                  type: object
            text/csv:
              example: 'side,price,size,exchange

                bid,20292.97,0.01501,1

                bid,20291.93,0.00218483,1

                ask,18445.61,0.22,1

                ask,18463.07,0.00234104,1

                ask,18464.83,0.04159475,1

                '
              schema:
                type: string
          description: Get current level 2 book for a ticker
        default:
          description: Unexpected error
      summary: Ticker Full Book (L2)
      tags:
      - crypto:snapshot
      x-polygon-deprecation:
        date: 1719838800000
      x-polygon-entitlement-allowed-timeframes:
      - description: Real Time Data
        name: realtime
      - description: 15 minute delayed data
        name: delayed
      x-polygon-entitlement-data-type:
        description: Aggregate data
        name: aggregates
      x-polygon-entitlement-market-type:
        description: Crypto data
        name: crypto
  /v2/snapshot/locale/global/markets/crypto/{direction}:
    get:
      description: 'Get the current top 20 gainers or losers of the day in cryptocurrency markets.

        <br />

        <br />

        Top gainers are those tickers whose price has increased by the highest percentage since the previous day''s close.

        Top losers are those tickers whose price has decreased by the highest percentage since the previous day''s close.

        <br />

        <br />

        Note: Snapshot data is cleared at 12am EST and gets populated as data is received from the exchanges.

        '
      operationId: GetCryptoSnapshotDirection
      parameters:
      - description: 'The direction of the snapshot results to return.

          '
        example: gainers
        in: path
        name: direction
        required: true
        schema:
          enum:
          - gainers
          - losers
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                status: OK
                tickers:
                - day:
                    c: 0.0374
                    h: 0.062377
                    l: 0.01162
                    o: 0.044834
                    v: 27313165.159427017
                    vw: 0
                  lastTrade:
                    c:
                    - 2
                    i: '517478762'
                    p: 0.0374
                    s: 499
                    t: 1604409649544
                    x: 2
                  min:
                    c: 0.062377
                    h: 0.062377
                    l: 0.062377
                    n: 2
                    o: 0.062377
                    t: 1684426740000
                    v: 35420
                    vw: 0
                  prevDay:
                    c: 0.01162
                    h: 0.044834
                    l: 0.01162
                    o: 0.044834
                    v: 53616273.36827199
                    vw: 0.0296
                  ticker: X:DRNUSD
                  todaysChange: 0.02578
                  todaysChangePerc: 221.858864
                  updated: 1605330008999
              schema:
                allOf:
                - description: The status of this request's response.
                  type: string
                - properties:
                    tickers:
                      description: An array of snapshot data for the specified tickers.
                      items:
                        properties:
                          day:
                            description: The most recent daily bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            type: object
                          fmv:
                            description: Fair market value is only available on Business plans. It is our proprietary algorithm to generate a real-time, accurate, fair market value of a tradable security. For more information, <a rel="nofollow" target="_blank" href="https://massive.com/contact">contact us</a>.
                            format: double
                            type: number
                          lastTrade:
                            description: The most recent trade for this ticker.
                            properties:
                              c:
                                description: The trade conditions.
                                items:
                                  type: integer
                                type: array
                              i:
                                description: 'The Trade ID which uniquely identifies a trade. These are unique per

                                  combination of ticker, exchange, and TRF. For example: A trade for AAPL

                                  executed on NYSE and a trade for AAPL executed on NASDAQ could potentially

                                  have the same Trade ID.

                                  '
                                type: string
                              p:
                                description: 'The price of the trade. This is the actual dollar value per whole share of

                                  this trade. A trade of 100 shares with a price of $2.00 would be worth a

                                  total dollar value of $200.00.

                                  '
                                format: double
                                type: number
                              s:
                                description: The size (volume) of the trade.
                                type: number
                              t:
                                description: The millisecond accuracy timestamp. This is the timestamp of when the trade was generated at the exchange.
                                type: integer
                              x:
                                description: "The exchange that this crypto trade happened on.  \nSee <a href=\"https://massive.com/docs/rest/crypto/market-operations/exchanges\">Exchanges</a> for a mapping of exchanges to IDs.\n"
                                type: integer
                            required:
                            - c
                            - i
                            - p
                            - s
                            - t
                            - x
                            type: object
                          min:
                            description: The most recent minute bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              n:
                                description: The number of transactions in the aggregate window.
                                type: integer
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              t:
                                description: The Unix millisecond timestamp for the start of the aggregate window.
                                type: integer
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            - t
                            - n
                            type: object
                          prevDay:
                            description: The previous day's bar for this ticker.
                            properties:
                              c:
                                description: The close price for the symbol in the given time period.
                                format: double
                                type: number
                              h:
                                description: The highest price for the symbol in the given time period.
                                format: double
                                type: number
                              l:
                                description: The lowest price for the symbol in the given time period.
                                format: double
                                type: number
                              o:
                                description: The open price for the symbol in the given time period.
                                format: double
                                type: number
                              v:
                                description: The trading volume of the symbol in the given time period.
                                format: double
                                type: number
                              vw:
                                description: The volume weighted average price.
                                format: double
                                type: number
                            required:
                            - o
                            - h
                            - l
                            - c
                            - v
                            - vw
                            type: object
                          ticker:
                            description: The exchange symbol that this item is traded under.
                            type: string
                          todaysChange:
                            description: The value of the change from the previous day.
                            format: double
                            type: number
                          todaysChangePerc:
                            description: The percentage change since the previous day.
                            format: double
                            type: number
                          updated:
                            description: The last updated timestamp.
                            type: integer
                        required:
                        - day
                        - lastTrade
                        - min
                        - prevDay
                        - ticker
                        - todaysChange
                        - todaysChangePerc
                        - updated
                        type: object
                      type: array
                  type: object
            text/csv:
              example: 'day_c,day_h,day_l,day_o,day_v,day_vw,lastTrade_c,lastTrade_i,lastTrade_p,lastTrade_s,lastTrade_t,lastTrade_x,day_c,day_h,day_l,day_o,day_v,day_vw,prevDay_c,prevDay_h,prevDay_l,prevDay_o,prevDay_v,prevDay_vw

                0.0374,0.062377,0.01162,0.044834,27313165.159427017,0,"[2]",517478762,0.0374,499,1604409649544,2,0.062377,0.062377,0.062377,0.062377,35420,0,0.01162,0.044834,0.01162,0.044834,53616273.36827199,0.0296

                '
              schema:
                type: string
          description: Get the current gainers / losers of the day
        default:
          description: Unexpected error
      summary: Gainers/Losers
      tags:
      - crypto:snapshot
      x-polygon-entitlement-allowed-timeframes:
      - description: Real Time Data
        name: realtime
      - description: 15 minute delayed data
        name: delayed
      x-polygon-entitlement-data-type:
        description: Aggregate data
        name: aggregates
      x-polygon-entitlement-market-type:
        description: Crypto data
        name: crypto
components:
  securitySchemes:
    apiKey:
      in: query
      name: apiKey
      type: apiKey
x-polygon-order:
  crypto:
    market:
    - launchpad: shared
      paths:
      - /v2/aggs/ticker/{cryptoTicker}/range/{multiplier}/{timespan}/{from}/{to}
    - launchpad: exclusive
      paths:
      - /v1/summaries
    - paths:
      - /v2/aggs/grouped/locale/global/market/crypto/{date}
    - paths:
      - /v1/open-close/crypto/{from}/{to}/{date}
    - paths:
      - /v2/aggs/ticker/{cryptoTicker}/prev
    - paths:
      - /v3/trades/{cryptoTicker}
    - paths:
      - /v1/historic/crypto/{from}/{to}/{date}
    - paths:
      - /v1/last/crypto/{from}/{to}
    - group: Snapshots
      paths:
      - /v2/snapshot/locale/global/markets/crypto/tickers
      - /v2/snapshot/locale/global/markets/crypto/{direction}
      - /v2/snapshot/locale/global/markets/crypto/tickers/{ticker}
      - /v2/snapshot/locale/global/markets/crypto/tickers/{ticker}/book
      - /v3/snapshot
    - group: Technical Indicators
      paths:
      - /v1/indicators/sma/{cryptoTicker}
      - /v1/indicators/ema/{cryptoTicker}
      - /v1/indicators/macd/{cryptoTicker}
      - /v1/indicators/rsi/{cryptoTicker}
    reference:
    - paths:
      - /v3/reference/tickers
    - paths:
      - /v1/marketstatus/upcoming
    - paths:
      - /v1/marketstatus/now
    - paths:
      - /v3/reference/conditions
    - paths:
      - /v3/reference/exchanges
  fx:
    market:
    - launchpad: shared
      paths:
      - /v2/aggs/ticker/{forexTicker}/range/{multiplier}/{timespan}/{from}/{to}
    - launchpad: exclusive
      paths:
      - /v1/summaries
    - paths:
      - /v2/aggs/grouped/locale/global/market/fx/{date}
    - paths:
      - /v2/aggs/ticker/{forexTicker}/prev
    - paths:
      - /v3/quotes/{fxTicker}
    - paths:
      - /v1/historic/forex/{from}/{to}/{date}
    - paths:
      - /v1/last_quote/currencies/{from}/{to}
    - paths:
      - /v1/conversion/{from}/{to}
    - group: Snapshots
      paths:
      - /v2/snapshot/locale/global/markets/forex/tickers
      - /v2/snapshot/locale/global/markets/forex/{direction}
      - /v2/snapshot/locale/global/markets/forex/tickers/{ticker}
      - /v3/snapshot
    - group: Technical Indicators
      paths:
      - /v1/indicators/sma/{fxTicker}
      - /v1/indicators/ema/{fxTicker}
      - /v1/indicators/macd/{fxTicker}
      - /v1/indicators/rsi/{fxTicker}
    reference:
    - paths:
      - /v3/reference/tickers
    - paths:
      - /v1/marketstatus/upcoming
    - paths:
      - /v1/marketstatus/now
    - paths:
      - /v3/reference/conditions
    - paths:
      - /v3/reference/exchanges
  indices:
    market:
    - launchpad: shared
      paths:
      - /v2/aggs/ticker/{indicesTicker}/range/{multiplier}/{timespan}/{from}/{to}
    - paths:
      - /v2/aggs/ticker/{indicesTicker}/prev
    - paths:
      - /v1/open-close/{indicesTicker}/{date}
    - group: Technical Indicators
      paths:
      - /v1/indicators/sma/{indicesTicker}
      - /v1/indicators/ema/{indicesTicker}
      - /v1/indicators/macd/{indicesTicker}
      - /v1/indicators/rsi/{indicesTicker}
    - group: Snapshots
      paths:
      - /v3/snapshot/indices
      - /v3/snapshot
    reference:
    - paths:
      - /v3/reference/tickers
    - paths:
      - /v3/reference/tickers/types
    - paths:
      - /v1/marketstatus/upcoming
    - paths:
      - /v1/marketstatus/now
  options:
    market:
    - launchpad: shared
      paths:
      - /v2/aggs/ticker/{optionsTicker}/range/{multiplier}/{timespan}/{from}/{to}
    - launchpad: exclusive
      paths:
      - /v1/summaries
    - paths:
      - /v1/open-close/{optionsTicker}/{date}
    - paths:
      - /v2/aggs/ticker/{optionsTicker}/prev
    - paths:
      - /v3/trades/{optionsTicker}
    - paths:
      - /v2/last/trade/{optionsTicker}
    - paths:
      - /v3/quotes/{optionsTicker}
    - group: Snapshots
      paths:
      - /v3/snapshot/options/{underlyingAsset}/{optionContract}
      - /v3/snapshot/options/{underlyingAsset}
      - /v3/snapshot
    - group: Technical Indicators
      paths:
      - /v1/indicators/sma/{optionsTicker}
      - /v1/indicators/ema/{optionsTicker}
      - /v1/indicators/macd/{optionsTicker}
      - /v1/indicators/rsi/{optionsTicker}
    reference:
    - paths:
      - /v3/reference/options/contracts/{options_ticker}
    - paths:
      - /v3/reference/options/contracts
    - paths:
      - /v3/reference/tickers
    - paths:
      - /v1/meta/symbols/{stocksTicker}/company
    - paths:
      - /v3/reference/tickers/{ticker}
    - paths:
      - /v2/reference/news
    - paths:
      - /v3/reference/tickers/types
    - paths:
      - /v1/marketstatus/upcoming
    - paths:
      - /v1/marketstatus/now
    - paths:
      - /v3/reference/conditions
    - paths:
      - /v3/reference/exchanges
  stocks:
    market:
    - launchpad: shared
      paths:
      - /v2/aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}
    - launchpad: exclusive
      paths:
      - /v1/summaries
    - paths:
      - /v2/aggs/grouped/locale/us/market/stocks/{date}
    - paths:
      - /v1/open-close/{stocksTicker}/{date}
    - paths:
      - /v2/aggs/ticker/{stocksTicker}/prev
    - paths:
      - /v3/trades/{stockTicker}
    - paths:
      - /v2/ticks/stocks/trades/{ticker}/{date}
    - paths:
      - /v2/last/trade/{stocksTicker}
    - paths:
      - /v3/quotes/{stockTicker}
    - paths:
      - /v2/ticks/stocks/nbbo/{ticker}/{date}
    - paths:
      - /v2/last/nbbo/{stocksTicker}
    - group: Snapshots
      paths:
      - /v2/snapshot/locale/us/markets/stocks/tickers
      - /v2/snapshot/locale/us/markets/stocks/{direction}
      - /v2/snapshot/locale/us/markets/stocks/tickers/{stocksTicker}
      - /v3/snapshot
    - group: Technical Indicators
      paths:
      - /v1/indicators/sma/{stockTicker}
      - /v1/indicators/ema/{stockTicker}
      - /v1/indicators/macd/{stockTicker}
      - /v1/indicators/rsi/{stockTicker}
    reference:
    - paths:
      - /v3/reference/tickers
    - paths:
      - /v1/meta/symbols/{stocksTicker}/company
    - paths:
      - /v3/reference/tickers/{ticker}
    - paths:
      - /vX/reference/tickers/{id}/events
    - paths:
      - /v2/reference/news
    - paths:
      - /v3/reference/tickers/types
    - paths:
      - /vX/reference/tickers/taxonomies
    - paths:
      - /v1/marketstatus/upcoming
    - paths:
      - /v1/marketstatus/now
    - group: SEC Filings
      paths:
      - /v1/reference/sec/filings
      - /v1/reference/sec/filings/{filing_id}
      - /v1/reference/sec/filings/{filing_id}/files
      - /v1/reference/sec/filings/{filing_id}/files/{file_id}
    - paths:
      - /v3/reference/splits
    - paths:
      - /v3/reference/dividends
    - paths:
      - /vX/reference/financials
    - paths:
      - /v3/reference/conditions
    - paths:
      - /v3/reference/exchanges
    - paths:
      - /v1/related-companies/{ticker}
    - paths:
      - /vX/reference/ipos
    - paths:
      - /vX/reference/short-interest/{identifier_type}/{identifier}
    - paths:
      - stocks/vX/listings
      - stocks/vX/listing/{identifier_type}/{identifier}
      - stocks/vX/listings/updates
